/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tributacao.main;

 import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
/**
 *
 * @author gusta
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
   /* public MainFrame() {
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private JLabel lblTitulo;
    private JLabel lblSenhaAtual;
    private JLabel lblSenhaLetreiro;
    private JLabel lblMesaAtual;
    private JLabel lblUltimasSenhas;
    private DefaultTableModel tableModel;
    private JTable lastCallsTable;

    public MainFrame() {
        setTitle("Painel de Senha");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(Color.BLUE);
        setLayout(new BorderLayout());

        lblTitulo = new JLabel("PREFEITURA MUNICIPAL DE SÃO JOÃO DA BOA VISTA SP");
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 36));
        lblTitulo.setForeground(Color.WHITE);
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(lblTitulo, BorderLayout.NORTH);

        JPanel pnlLeft = new JPanel(new GridLayout(3, 1));
        pnlLeft.setPreferredSize(new Dimension(750, 0));
        getContentPane().add(pnlLeft, BorderLayout.WEST);

        lblSenhaLetreiro = new JLabel("TRIBUTAÇÃO");
        lblSenhaLetreiro.setFont(new Font("Arial",Font.ROMAN_BASELINE,100));
        lblSenhaLetreiro.setHorizontalAlignment(SwingConstants.CENTER);
        pnlLeft.add(lblSenhaLetreiro);
        
        lblSenhaAtual = new JLabel("Senha Atual: ");
        lblSenhaAtual.setFont(new Font("Arial", Font.BOLD, 200));
        lblSenhaAtual.setForeground(Color.BLACK);
        lblSenhaAtual.setHorizontalAlignment(SwingConstants.CENTER);
        pnlLeft.add(lblSenhaAtual);

        lblMesaAtual = new JLabel("Mesa:");
        lblMesaAtual.setFont(new Font("Arial", Font.BOLD, 32));
        lblMesaAtual.setForeground(Color.BLACK);
        lblMesaAtual.setHorizontalAlignment(SwingConstants.CENTER);
        pnlLeft.add(lblMesaAtual);

        JPanel pnlRight = new JPanel(new BorderLayout());
        pnlRight.setBackground(Color.RED);
        getContentPane().add(pnlRight, BorderLayout.CENTER);

        lblUltimasSenhas = new JLabel("Últimas Senhas Chamadas:");
        lblUltimasSenhas.setFont(new Font("Arial", Font.BOLD, 24));
        lblUltimasSenhas.setForeground(Color.WHITE);
        
        pnlRight.add(lblUltimasSenhas, BorderLayout.NORTH);

        tableModel = new DefaultTableModel(new Object[]{"Senha", "Mesa"}, 0);
        lastCallsTable = new JTable(tableModel);
        lastCallsTable.setFont(new Font("Arial", Font.PLAIN, 18));
        lastCallsTable.setForeground(Color.WHITE);
        lastCallsTable.setBackground(Color.BLUE);
                        
        JScrollPane scrollPane = new JScrollPane(lastCallsTable);
        pnlRight.add(scrollPane, BorderLayout.CENTER);

        JButton btnChamarSenha = new JButton("Chamar Senha");
        btnChamarSenha.setFont(new Font("Arial", Font.BOLD, 20));
        btnChamarSenha.setForeground(Color.WHITE);
        btnChamarSenha.setBackground(Color.BLACK);
        btnChamarSenha.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                chamarSenha();
                //Toolkit.getDefaultToolkit().beep();
                Mp3Player.iniciaSom();                                  
            }
        });
        pnlRight.add(btnChamarSenha, BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void chamarSenha() {
        String chamada = Main.chamarSenha();
        lblSenhaAtual.setText(chamada.substring(0, 3));
        lblMesaAtual.setText(chamada.substring(chamada.indexOf("Mesa")));
        tableModel.addRow(new Object[]{chamada.substring(0, 3), chamada.substring(chamada.indexOf("Mesa"))});
        if (tableModel.getRowCount() > 6) {
            tableModel.removeRow(0);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

